eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

server:
    port: 8311

spring:
    application:
        name: review
    cloud:
        config:
            enabled: false
        import-check:
            enabled: false
    profiles:
        active: native

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/Drivers
        username: postgres
        password: dren123
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    data:
        mongodb:
            username: root
            password: password
            host: localhost
            port: 27017
            database: mongodb
            authentication-database: admin

user-service:
    url: http://localhost:8111/api/v1/user
driver-service:
    url: http://localhost:8211/driver
