eureka:
  instance:
    name: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



server:
  port: 8444
spring:
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false
  profiles:
    active: native
  application:
    name: ride
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rides
    username: postgres
    password: dren123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  data:
#    mongodb:
#      username: root
#      password: password
#      host: localhost
#      port: 27017
#      database: mongodb
#      authentication-database: admin

user-service:
  url: http://localhost:8111/api/v1/user
driver_service:
  url: http://localhost:8211/api/v1/driver
