eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8211
spring:
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false
  profiles:
    active: native
  application:
    name: drivers
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/drivers
    username: postgres
    password: altin1234
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


user-service:
  url: http://localhost:8111/api/v1/user