eureka:
  instance:
    name: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8111
spring:
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false
  profiles:
    active: native
  application:
    name: users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: altin1234
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379

ride-service:
  url: http://localhost:8444/api/v1/ride
driver-service:
  url: http://localhost:8211/api/v1/driver


#logging:
#  level:
#    org.springframework.web.socket: DEBUG
#    org.springframework.messaging.simp: DEBUG
