spring:
  data:
    mongodb:
      username: root
      password: password
      host: localhost
      port: 27017
      database: communicationdb
      authentication-database: admin

server:
  port: 8088