eureka:
  instance:
    name: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8314

spring:
  websocket:
    path: /ws
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false
  profiles:
    active: native
  application:
    name: communication

  data:
    mongodb:
      username: root
      password: password
      host: localhost
      port: 27017
      database: communicationdb
      authentication-database: admin

user-service:
#  url: http://localhost:8111/user
  url: http://localhost:8111
